name: Rust

on: [ "push" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        target: wasm32-unknown-unknown,wasm32-wasi
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose --workspace
    - name: Clippy
      run: cargo clippy --verbose --workspace -D warnings
    - name: Run tests
      run: cargo test --verbose --workspace
